// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSM5GBzhxePMEBqV_HVucrAH5qjsEVLGQ',
    appId: '1:604042435953:web:49db60855cf39fe8cb2ad0',
    messagingSenderId: '604042435953',
    projectId: 'ibank-93b15',
    authDomain: 'ibank-93b15.firebaseapp.com',
    storageBucket: 'ibank-93b15.firebasestorage.app',
    measurementId: 'G-RWJLYNETX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6qZru2aNubJn2TSpISQkggT5vGewe4E8',
    appId: '1:604042435953:android:eed65ce9be8a5295cb2ad0',
    messagingSenderId: '604042435953',
    projectId: 'ibank-93b15',
    storageBucket: 'ibank-93b15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW4oisYs43lzcJlIC5CZsO9NF0zbPH5aU',
    appId: '1:604042435953:ios:0290bd62854b1692cb2ad0',
    messagingSenderId: '604042435953',
    projectId: 'ibank-93b15',
    storageBucket: 'ibank-93b15.firebasestorage.app',
    iosClientId: '604042435953-kg0emopedrld6s6nmvcm37fqnmnlcs0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.iBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW4oisYs43lzcJlIC5CZsO9NF0zbPH5aU',
    appId: '1:604042435953:ios:0290bd62854b1692cb2ad0',
    messagingSenderId: '604042435953',
    projectId: 'ibank-93b15',
    storageBucket: 'ibank-93b15.firebasestorage.app',
    iosClientId: '604042435953-kg0emopedrld6s6nmvcm37fqnmnlcs0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.iBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSM5GBzhxePMEBqV_HVucrAH5qjsEVLGQ',
    appId: '1:604042435953:web:d6da84d4758abc2ecb2ad0',
    messagingSenderId: '604042435953',
    projectId: 'ibank-93b15',
    authDomain: 'ibank-93b15.firebaseapp.com',
    storageBucket: 'ibank-93b15.firebasestorage.app',
    measurementId: 'G-QSYPXS6T65',
  );
}
